import React from "react";
import Head from "next/head";
import { Navbar } from "../../components/ui/Navbar";
import { Footer } from "../../components/Footer";

interface NeelKamalProps {}

const NeelKamal: React.FC<NeelKamalProps> = ({}) => {
    return (
        <div>
            <Head>
                <title>
                    Mamta Kothari | Collections | NeelKamal Collection
                </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className="p-10">
                <div
                    style={{
                        boxShadow: "0px 0px 30px 0px #cccac1",
                    }}
                    className="flex flex-col md:flex-row items-center justify-center max-w-4xl mx-auto p-4 md:p-7 rounded-sm"
                >
                    <div className="md:w-5/12">
                        <img src="https://sunitashekhawat.com/skin/frontend/flamingo/default/images/collection-img1.jpg" />
                    </div>
                    <div className="md:w-7/12 p-6">
                        <img
                            className="mx-auto"
                            src="https://sunitashekhawat.com/skin/frontend/flamingo/default//images/pattern-img5.png"
                        />
                        <p className="text-3xl pfr text-center text-purple my-3">
                            {"'"}THE NEELKAMAL{"'"}
                        </p>
                        <p className="text-center text-purple pfr">
                            The Neelkamal collection is pure hand drawn detailed
                            jewellery with lotus petals and leaves in shades of
                            soft pink and white. Each piece displays high
                            quality workmanship and fine usage of eclectic
                            stones.
                        </p>
                    </div>
                </div>
                <img
                    className="md:max-w-3xl mx-auto my-12"
                    src="https://sunitashekhawat.com/skin/frontend/flamingo/default/images/collection-img2.jpg"
                />
                <img
                    className="mx-auto h-8 w-auto"
                    src="https://sunitashekhawat.com/skin/frontend/flamingo/default/images/comma-img.png"
                />
                <p className="max-w-md mt-5 italic text-lg mx-auto text-center pfr text-purple">
                    The challenge and conversely the strength of the brand lies
                    in preserving the old world charm, while reinventing the
                    sensibility for contemporary time and future.
                </p>
                <div className="my-20">
                    <img
                        className="mx-auto"
                        src="https://sunitashekhawat.com/skin/frontend/flamingo/default//images/pattern-img5.png"
                    />
                    <p className="text-2xl pfr text-center text-purple my-3">
                        THE COLLECTION
                    </p>
                    <div className="my-12 max-w-4xl carousel mx-auto">
                        <div className="flex flex-col carousel-item w-full md:w-[30%]">
                            <img src="https://sunitashekhawat.com/skin/frontend/flamingo/default/images/collection-img3.png" />
                            <p
                                style={{ fontSize: "14px" }}
                                className="text-center mt-7 text-purple font-medium got ls-2"
                            >
                                EARRINGS
                            </p>
                        </div>
                        <div className="flex flex-col carousel-item w-full md:w-[30%]">
                            <img src="https://sunitashekhawat.com/skin/frontend/flamingo/default/images/collection-img4.png" />
                            <p
                                style={{ fontSize: "14px" }}
                                className="text-center mt-7 text-purple font-medium got ls-2"
                            >
                                BANGLE
                            </p>
                        </div>
                        <div className="flex flex-col carousel-item w-full md:w-[30%]">
                            <img src="https://sunitashekhawat.com/skin/frontend/flamingo/default/images/collection-img5.png" />
                            <p
                                style={{ fontSize: "14px" }}
                                className="text-center mt-7 text-purple font-medium got ls-2"
                            >
                                RING
                            </p>
                        </div>
                        <div className="flex flex-col carousel-item w-full md:w-[30%]">
                            <img src="https://sunitashekhawat.com/skin/frontend/flamingo/default/images/collection-img12.png" />
                            <p
                                style={{ fontSize: "14px" }}
                                className="text-center mt-7 text-purple font-medium got ls-2"
                            >
                                EARRINGS
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <Footer />
        </div>
    );
};

export default NeelKamal;
