import React from "react";
import Head from "next/head";
import { Navbar } from "../components/ui/Navbar";
import { Footer } from "../components/Footer";

interface CampaignsProps {}

const Campaigns: React.FC<CampaignsProps> = ({}) => {
    return (
        <div>
            <Head>
                <title>Sunita Shekhawat - Campaign</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className="p-6">
                <img
                    className="mx-auto mb-2"
                    src="https://sunitashekhawat.com/skin/frontend/flamingo/default/images/pattern-img5.png"
                />
                <p className="text-2xl pfr text-center text-purple">
                    LONGBOOKS
                </p>
                <div className="flex flex-col md:flex-row items-center my-5 md:p-3 bg-white">
                    <div className="md:w-4/6 w-full">
                        <img src="https://sunitashekhawat.com/skin/frontend/flamingo/default/images/campaign-img6.jpg" />
                    </div>
                    <div className="md:w-2/6 md:p-3.5 p-2">
                        <p className="text-xl pfr text-center text-gold">
                            DAMAK
                        </p>
                        <p className="text-sm pfr text-center text-gold my-2">
                            Damak is the radiance of self-acceptance. The lustre
                            of life-lessons learned with gratitude, joy and
                            humility. In its animated glimmer, it is the blazing
                            dance of self-realisation, of celebrating the return
                            to one{"’"}s authentic self.{" "}
                        </p>
                        <p className="text-sm pfr text-center text-gold my-2">
                            Damak simmers and flows over in the grounding warmth
                            of our favourite rituals: those time- honoured rites
                            of passage that guide a little girl with stars in
                            her eyes through to maidenhood, when, slowly, those
                            stars begin to take shape as gems of grace, settling
                            on her ears and her forehead; her neck and her
                            fingers; her wrists and her ankles.
                        </p>
                        <p className="text-sm pfr text-center text-gold my-2">
                            In true Sunita Shekhawat style, Meenakari celebrates
                            familiar and well-loved shades of royal blue,
                            firoza, or green.
                        </p>
                    </div>
                </div>
                <div className="flex flex-col md:flex-row items-center my-5 md:p-3 bg-white">
                    <div className="md:w-2/6 md:p-3.5 p-2">
                        <p className="text-xl pfr text-center text-gold">
                            THE OLD MYSTIQUE CHARM
                        </p>
                        <p className="text-sm pfr text-center text-gold my-2">
                            A narrative woven entirely in colour, where nature,
                            history, art and craft collaborate in sublime
                            confluence, the campaign represents a refreshingly
                            original rethink of traditional Meenakari work.
                        </p>
                        <p className="text-sm pfr text-center text-gold my-2">
                            The extravagance of the jewels is not only a
                            reflection of Sunita Shekhawat’s roots in royalty
                            but also to her quest for work that reflects beauty
                            and dignity. Kundan – Meenakari Jewellery by the
                            very virtue of its design, craftsmanship and rich
                            history, is considered an artifact. The challenge
                            lies in presenting her beauty of the old form, while
                            reinventing the designs for a contemporary age and
                            audience.
                        </p>
                    </div>
                    <div className="md:w-4/6 w-full">
                        <img src="https://sunitashekhawat.com/skin/frontend/flamingo/default/images/campaign-img5.jpg" />
                    </div>
                </div>
                <div className="flex flex-col md:flex-row items-center my-5 md:p-3 bg-white">
                    <div className="md:w-4/6 w-full">
                        <img src="https://sunitashekhawat.com/skin/frontend/flamingo/default/images/campaign-img1.jpg" />
                    </div>
                    <div className="md:w-2/6 md:p-3.5 p-2">
                        <p className="text-xl pfr text-center text-gold">
                            AISLE OF THE SKY
                        </p>
                        <p className="text-sm pfr text-center text-gold my-2">
                            The Subtle elegance and stillness of nature that
                            envelops the regions of Ladakh, have been a source
                            of constant motivation that drives the design
                            essence of the brand.
                        </p>
                        <p className="text-sm pfr text-center text-gold my-2">
                            Just like the Deep blue Lake of Ladakh, the
                            collection has been hand - painted in rich shades of
                            Meenakari further highlighted with decorative pearls
                            and polkis studded in geometric shapes,
                            strengthening the beauty of gold and blending the
                            modern layout with traditional aesthetics and
                            outlook.
                        </p>
                    </div>
                </div>
                <div className="flex flex-col md:flex-row items-center my-5 md:p-3 bg-white">
                    <div className="md:w-2/6 md:p-3.5 p-2">
                        <p className="text-xl pfr text-center text-gold">
                            FOREST GODDESS
                        </p>
                        <p className="text-sm pfr text-center text-gold my-2">
                            Personifying the mystic charm of the forest through
                            the bold and appeasing beauty of the modern day
                            woman.
                        </p>
                        <p className="text-sm pfr text-center text-gold my-2">
                            The jewels speak through the realism and innovative
                            use of elements engraved in the collections, that
                            capture woodland tones alongside the palettes of
                            vibrant plants. The philosophy behind the Sunita
                            Shekhawat Woman resonates with the Forest Goddess -
                            bold, affectionate, and fearless. Let the jewel
                            adorn you, not overpower you.
                        </p>
                    </div>
                    <div className="md:w-4/6 w-full">
                        <img src="https://sunitashekhawat.com/skin/frontend/flamingo/default/images/campaign-img2.jpg" />
                    </div>
                </div>
                <div className="flex flex-col md:flex-row items-center my-5 md:p-3 bg-white">
                    <div className="md:w-4/6 w-full">
                        <img src="https://sunitashekhawat.com/skin/frontend/flamingo/default/images/campaign-img3.jpg" />
                    </div>
                    <div className="md:w-2/6 md:p-3.5 p-2">
                        <p className="text-xl pfr text-center text-gold">
                            THE WATER MAIDEN
                        </p>
                        <p className="text-sm pfr text-center text-gold my-2">
                            The Water Maiden, the way Ocean glistens to the rays
                            of the sun and the fresh aquamarine hues of the
                            marine bodies is quite similar to the exuberant
                            gleam of the diamond and polkis used at the ateliers
                            of Sunita Shekhawat Jaipur.
                        </p>
                        <p className="text-sm pfr text-center text-gold my-2">
                            Comprising of both, the beauty of nature and our
                            timeless masterpieces based on the traditional art
                            of Meenakari, with a fresh and contemporary
                            aesthetic and design philosophy. Sunita Shekhawat
                            Jewels, family heirlooms to be passed on through
                            generations, set in gold and bejeweled with uncut
                            diamonds and polkis for any bridal attire.
                        </p>
                    </div>
                </div>
                <div className="flex flex-col md:flex-row items-center my-5 md:p-3 bg-white">
                    <div className="md:w-2/6 md:p-3.5 p-2">
                        <p className="text-xl pfr text-center text-gold">
                            SOLAH SHRINGAR
                        </p>
                        <p className="text-sm pfr text-center text-gold my-2">
                            A series of strikingly simple and cherished
                            ensemble. A source of inspiration and solace to the
                            wearer and the beholder.A perfect example of the
                            unbroken continuity in styles in the Indian
                            Jewellery tradition.
                        </p>
                        <p className="text-sm pfr text-center text-gold my-2">
                            The collection is harmoniously juxtaposed to
                            complete a perfectly balanced look, almost similar
                            to a celestial garden with flowers of every hue. We
                            believe in the value of versatility, featuring the
                            traditional collection, enameled with polki,
                            reflects the lavish splendor of accoutrements, a
                            part of the Solah Shringar.
                        </p>
                    </div>
                    <div className="md:w-4/6 w-full">
                        <img src="https://sunitashekhawat.com/skin/frontend/flamingo/default/images/campaign-img4.jpg" />
                    </div>
                </div>
            </div>
            <Footer />
        </div>
    );
};

export default Campaigns;
