import React from "react";
import Head from "next/head";
import { Navbar } from "../components/ui/Navbar";
import { Footer } from "../components/Footer";

interface CollectionsProps {}

const Collections: React.FC<CollectionsProps> = ({}) => {
    return (
        <div>
            <Head>
                <title>Mamta Kothari - Contact</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <Footer />
        </div>
    );
};

export default Collections;
