import React from "react";
import Head from "next/head";
import { Footer } from "../components/Footer";
import { Navbar } from "../components/ui/Navbar";

interface storesProps {}

const Stores: React.FC<storesProps> = ({}) => {
    return (
        <div>
            <Head>
                <title>Sunita Shekhawat - Stores</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className="mx-11 flex flex-col md:flex-row items-center">
                <div className="w-full p-5 text-center">
                    <img src="https://sunitashekhawat.com/skin/frontend/flamingo/default/images/store2.jpg" />
                    <p className="mt-6 text-gold got font-medium">JAIPUR</p>
                    <p className="my-2 text-gold got text-sm">
                        B-6B, PRITHVIRAJ ROAD,
                        <br />
                        JAIPUR - 302001
                    </p>
                    <p className="mt-5 text-sm text-gold got font-medium">
                        +91 141 2361385 / 95
                    </p>
                    <button className="ml-auto mr-auto mt-5 border transition duration-auto got text-purple border-purple max-w-max text-sm p-2.5 font-semibold hover:bg-purple hover:text-white">
                        VIEW MAP
                    </button>
                </div>
                <div className="w-full p-5 text-center">
                    <img src="https://sunitashekhawat.com/skin/frontend/flamingo/default/images/store1.jpg" />
                    <p className="mt-6 text-gold got font-medium">DELHI</p>
                    <p className="my-2 text-gold got text-sm">
                        D - 18, DEFENCE COLONY,
                        <br />
                        NEW DELHI - 110024
                    </p>
                    <p className="mt-5 text-sm text-gold got font-medium">
                        +91 11 24331395 / 97
                    </p>
                    <button className="ml-auto mr-auto mt-5 border transition duration-auto got text-purple border-purple max-w-max text-sm p-2.5 font-semibold hover:bg-purple hover:text-white">
                        VIEW MAP
                    </button>
                </div>
                <div className="w-full p-5 text-center">
                    <img src="https://sunitashekhawat.com/skin/frontend/flamingo/default/images/store3.jpg" />
                    <p className="mt-6 text-gold got font-medium">
                        DLF EMPORIO
                    </p>
                    <p className="my-2 text-gold got text-sm">
                        DLF EMPORIO, VASANT KUNJ,
                        <br />
                        NEW DELHI - 110022
                    </p>
                    <p className="mt-5 text-sm text-gold got font-medium">
                        +91 11 40114377
                    </p>
                    <button className="ml-auto mr-auto mt-5 border transition duration-auto got text-purple border-purple max-w-max text-sm p-2.5 font-semibold hover:bg-purple hover:text-white">
                        VIEW MAP
                    </button>
                </div>
            </div>
            <Footer />
        </div>
    );
};

export default Stores;
